# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20170121_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
