# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_items',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice_items',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
