# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intransaction',
            name='date',
            field=models.TimeField(verbose_name='date'),
        ),
    ]
