# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20170117_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intransaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outtransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
