# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20170121_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='intransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='outtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
    ]
